#!/usr/bin/env bash

# very cheap check if parameters are set
[[ $# -lt 2 ]] && { echo "usage: $0 [init,start,update,keygen,deploy,rkeup,rkeremove] [CUSTOMER]" ; exit 1 ; }

MODE=${1}
CUSTOMER=${2}

SELF_DIR=$(git rev-parse --show-toplevel)
export SSHDIR=${SELF_DIR}/${CUSTOMER}/.ssh

JQ="docker run -i --rm 300481/jq:v1.6"
URL_READINESS="localhost:8080/api/readiness"

runInit() {
    [[ -d ${SELF_DIR}/../file-permission-hooks ]] && return
    git clone https://github.com/300481/file-permission-hooks.git ${SELF_DIR}/../file-permission-hooks
    for HOOK in $(find ${SELF_DIR}/../file-permission-hooks/ -maxdepth 1 -executable -type f) ; do
        ln -s ${HOOK} ${SELF_DIR}/.git/hooks/${HOOK##*/}
    done
    git checkout $(git rev-parse --abbrev-ref HEAD)
    exit
}

startApp() {
    export APPVER=$(docker run -i --rm --name yq 300481/yq:v2.4.0 appver < ${CUSTOMER}/config.yaml)
    export DNSVER=$(docker run -i --rm --name yq 300481/yq:v2.4.0 dnsver < ${CUSTOMER}/config.yaml)
    docker-compose up -d
    update
}

update() {
    uploadTemplates
    uploadConfig
    uploadClusterConfig
}

keyGen() {
    if [[ -f ${CUSTOMER}/.ssh/id_rsa ]] ; then
        return
    fi
    if ! [[ -d ${SSHDIR} ]] ; then
        mkdir -p ${SSHDIR}
        chmod 700 ${SSHDIR}
    fi
    ssh-keygen -t rsa -b 4096 -f ${SSHDIR}/id_rsa -P "" -C "" -q
    return
}

uploadTemplates() {
    cd ${CUSTOMER}
    for TEMPLATE in $(find api -type f) ; do
        curl -X POST -d "$(< ${TEMPLATE})" localhost:8080/${TEMPLATE}
    done
    cd ..
}

uploadConfig() {
    export GW=$(ip route | awk '/default/ { print $3 }')
    export IP=$(ip route | awk '/default/ { print $9 }')
    export PUBKEY=$(< ${SSHDIR}/id_rsa.pub)
    curl -X POST -d "$(envsubst < ${CUSTOMER}/config.yaml)" localhost:8080/api/config
}

uploadClusterConfig() {
    if [[ -f ${CUSTOMER}/cluster.json ]] ; then
        curl -X POST -d "$(< ${CUSTOMER}/cluster.json)" localhost:8080/api/cluster
    fi
}

deploy() {
    runInit
    keyGen
    startApp
    echo -n "Waiting for cluster deployment..."
    while [[ $(curl -s ${URL_READINESS} | ${JQ} .connect) == false ]] ; do
        echo -n "."
        sleep 10
    done
    echo "OK"
    echo "Install Rancher Kubernetes Engine"
    echo ""
    echo ""
    echo "Getting 3141 cluster config"    
    curl -s localhost:8080/api/cluster > ${CUSTOMER}/cluster.json
    echo "Getting rke cluster config"    
    curl -s localhost:8080/api/tpl/cluster > ${CUSTOMER}/cluster.yml
    sleep 2
    rkeUp
}

rkeUp() {
    export RKEVER=$(docker run -i --rm --name yq 300481/yq:v2.4.0 rkever < ${CUSTOMER}/config.yaml)
    docker run -it --rm --name rke -v $(pwd)/${CUSTOMER}:/data -v ${SSHDIR}:/.ssh 300481/rke:${RKEVER} up
}

rkeRemove() {
    export RKEVER=$(docker run -i --rm --name yq 300481/yq:v2.4.0 rkever < ${CUSTOMER}/config.yaml)
    docker run -it --rm --name rke -v $(pwd)/${CUSTOMER}:/data -v ${SSHDIR}:/.ssh 300481/rke:${RKEVER} remove
}

case ${MODE} in
    init)
        runInit
        ;;
    keygen)
        keyGen
        ;;
    start)
        runInit
        startApp
        ;;
    update)
        update
        ;;
    deploy)
        deploy
        ;;
    rkeup)
        rkeUp
        ;;
    rkeremove)
        rkeRemove
        ;;
    *)
        exit
        ;;
esac
