boothost: ${IP}
clustername: cluster
startcidr: 192.168.1.150/24
nodecount: 1
publickey: ${PUBKEY}
gateway: ${GW}
mtu: 1500
dhcp: false
nameservers:
- ${GW}
appver: v0.5.10
dnsver: v0.2.2
rkever: v0.1.18
