settingsver: 1
dnsmasqrange: 192.168.1.1
boothost: ${IP}
boothostport: 8080
clustername: cluster
startcidr: 192.168.1.150/24
nodecount: 3
publickey: ${PUBKEY}
gateway: ${GW}
mtu: 1500
dhcp: false
nameservers:
- ${GW}
