settingsver: 1
dnsmasqrange: 192.168.1.1
boothost: 192.168.1.6
boothostport: 8080
clustername: cluster
startcidr: 192.168.1.150/24
nodecount: 3
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYGESau28+g8LfAQtZ0uMl1cf6DFzkIYnfyNLXiGpO1CAUrmlJOIkmEqqLKWYrU5lDlBH+mh8mU441VkiOBewyJ1wCrN8PSIuaU9pdS/dT1MgmUK5+b47QgeeK/WDGsW4UgTKuBOSQIkyuYwyVUz9oJHq4ygjUQW/1+W3j8Lgn5gZ0gZJJxvRPzHFG6/TPH1uZPhzOPFsqqMH+dDaf5vHYN2HbRNbjzpM8wHuLEbR+eM4btZ057ZajbIJy3hiQTGkRW0jSvyTVtpC5/ECo9TbAw2JOTP+LjFmn+tdUF0vHYHCnPPinBt4Cr7WX/XxcOlFuVWMX/dFMdVe7Ki4X1DJcjIKzeF3Ai5xGvmUqnTXprYOQW3U0CFXzkt7YTrFXcEzpu6FhQB53Ri/0FJEyfeVinu/n8aHKx3EraY6xycs613MOeaN4fqS893zefdQ1nKI1pxdTmTDhuqoXIFoGJ55yp2X8R5bfLwQy+H7WCNl7/nFSc2jESqYVM1pRFQ5itIErRxSFPscQnl2bz6ewarzHfEVaiR3pchOrzf8GgYyc8Eb6ywluD8eLUrVK8SNDMSjz9ibgwR6Wfr4NUEPFkW8XYLoXAD4lR5jMdzMbs6lhqBOtfzrrlLB0FZlyc8a65ntl9lyqXlmBnwtfDf/0AVjYqUTFl1+6opwLQqC89MMHKw==
gateway: 192.168.1.254
mtu: 1500
dhcp: false
nameservers:
- 192.168.1.254
