settingsver: 1
dnsmasqrange: 192.168.0.1
boothost: 192.168.0.46
boothostport: 8080
clustername: cluster
startcidr: 192.168.0.50/24
nodecount: 1
publickey: ${PUBKEY}
gateway: 192.168.0.1
mtu: 1500
dhcp: false
nameservers:
- 192.168.0.1
