boothost: ${IP}
clustername: cluster
startcidr: 192.168.0.50/24
nodecount: 1
publickey: ${PUBKEY}
gateway: ${GW}
mtu: 1500
dhcp: false
nameservers:
- ${GW}
appver: v0.6.3
dnsver: v0.2.2
rkever: v0.1.18
